# Usar imagen oficial de Python ligera
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema necesarias (opcional pero útil)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copiar el archivo de requerimientos
COPY requirements.txt .

# Instalar las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY build_db.py .
COPY LetrasTXT/ LetrasTXT/

# Construir la base de datos dentro de la imagen
RUN python build_db.py

# Exponer el puerto de Uvicorn
EXPOSE 8000

# Comando para arrancar la aplicación API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
