# -*- coding: utf-8 -*-
"""Función_clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zBEWbhmDIlfLAccfawYnw-GA8NpVLaz
"""

# LIBRERÍAS
import spacy

nlp = spacy.load("es_core_news_md")

# DICCIONARIO INDÍGENA

PALABRAS_INDIGENAS = {
    "ihuatsï", "misitu", "sapichu", "turhípiti", "pireri",
    "kukuta", "uarhi", "uichu", "túkuru", "auani",
    "kani", "jarhámuta", "uátsï", "uátsi",
    "axuni", "kuini", "tzintzun", "kuaraki",
    "kurhikaueri", "kutsi", "kutzi", "koki", "kuanasi",
    "kuiris", "japunda", "japonda", "akuitse"
}

STOPWORDS_EXTRA = {
    "el", "la", "los", "las", "lo", "uno", "este", "ese", "esta", "eso", "él",
    "a", "de", "del", "al", "en", "con", "por", "para", "sin", "sobre", "entre", "hasta",
    "y", "o", "ni", "pero", "porque", "si", "como", "cuando",
    "yo", "tú", "tu", "me", "te", "se", "le", "nos", "mi", "mis", "su", "sus", "otros", "que", "qué",
    "ya", "muy", "más", "tan", "todo", "todos", "bien", "así", "donde", "ay",
    "un", "una", "no", "es", "ir", "ser", "lai", "ver", "hay",
}

def clasificar_oov(
    texto,
    nlp,
    umbral_estandar=5.0,
    umbral_regional=18.0,
    stopwords_extra=None,
    PALABRAS_INDIGENAS=None
):

    if stopwords_extra is None:
        stopwords_extra = set()

    if PALABRAS_INDIGENAS is None:
      PALABRAS_INDIGENAS = set()

    doc = nlp(texto.lower())

    n_total = 0
    n_oov = 0
    contiene_indigena = False
    for token in doc:

        if (
            token.is_alpha
            and len(token) > 2
            and not token.is_stop
            and token.lemma_ not in stopwords_extra
            and token.text not in stopwords_extra
        ):

            n_total += 1

            if token.is_oov:
                n_oov += 1

            # Detectar palabras indígenas conocidas
            if (token.text in PALABRAS_INDIGENAS or token.lemma_ in PALABRAS_INDIGENAS):
                contiene_indigena = True


    pct_oov = 0 if n_total == 0 else 100 * n_oov / n_total

    if contiene_indigena:
        return "LENGUA_INDIGENA"
    if pct_oov < umbral_estandar:
        return "ESPAÑOL_ESTANDAR"
    elif pct_oov < umbral_regional:
        return "ESPAÑOL_REGIONAL"
    else:
        return "LENGUA_INDIGENA"

"""## Carga de las canciones"""

import os, re, random, hashlib, json, time
import pandas as pd
import numpy as np
import openpyxl

# Procesamiento de las canciones

RUTA_BASE       = "/content/drive/MyDrive/LetrasTXT"   # Cambia si es necesario

# Palabras de corte
PALABRAS_CORTE = ["Dura:", "Tema:", "Personajes:"]

RE_AUTOR      = re.compile(r'^autor\s*[:\.]?\s*', re.IGNORECASE)
RE_PARENTESIS = re.compile(r'\(.*?\)', re.DOTALL)

from google.colab import drive
drive.mount('/content/drive')

# Funciones de limpieza

def limpiar_parentesis(texto):
    def reemplazar(match):
        return match.group(0) if len(match.group(0)) >= 19 else ""
    return RE_PARENTESIS.sub(reemplazar, texto)

def procesar_archivo_raw(texto_raw, nombre_cancion):
    lineas     = texto_raw.split("\n")
    autor      = None
    idx_inicio = 0
    for i, linea in enumerate(lineas):
        if linea.strip().lower() == nombre_cancion.strip().lower():
            idx_inicio = i + 1
            break
    while idx_inicio < len(lineas) and not lineas[idx_inicio].strip():
        idx_inicio += 1
    if idx_inicio < len(lineas) and RE_AUTOR.match(lineas[idx_inicio].strip()):
        autor      = RE_AUTOR.sub("", lineas[idx_inicio]).strip().rstrip(".")
        idx_inicio += 1
        while idx_inicio < len(lineas) and not lineas[idx_inicio].strip():
            idx_inicio += 1
    texto_letra = "\n".join(lineas[idx_inicio:])
    texto_letra = limpiar_parentesis(texto_letra)
    return autor, texto_letra

def cortar_metadata(texto):
    for marca in PALABRAS_CORTE:
        if marca in texto:
            texto = texto.split(marca)[0]
    return re.sub(r"\s+", " ", texto.strip())

# Corpus crudo
registros = []

for album in sorted(os.listdir(RUTA_BASE)):
    ruta_album = os.path.join(RUTA_BASE, album)
    if not os.path.isdir(ruta_album):
        continue
    for archivo in sorted(os.listdir(ruta_album)):
        if not archivo.endswith(".txt"):
            continue
        cancion = archivo.replace(".txt", "")
        with open(os.path.join(ruta_album, archivo), "r", encoding="utf-8") as f:
            texto_raw = f.read()
        autor, texto_sin_encabezado = procesar_archivo_raw(texto_raw, cancion)
        texto_limpio = cortar_metadata(texto_sin_encabezado)
        texto_limpio = texto_limpio.replace("|", "").replace("-", "")
        registros.append({
            "album":       album,
            "cancion":     cancion,
            "autor":       autor,
            "texto_crudo": texto_limpio,
        })

corpus_crudo = pd.DataFrame(registros)

corpus_crudo.head(5)

# Ejecucion de la función
corpus_crudo["Clasifiacion"] = corpus_crudo.apply(
    lambda row: clasificar_oov(row['texto_crudo'], nlp, stopwords_extra = STOPWORDS_EXTRA, PALABRAS_INDIGENAS = PALABRAS_INDIGENAS),
    axis=1
)

corpus_crudo['Clasifiacion'].value_counts()

corpus_crudo.head(5)

corpus_crudo.to_excel(
    r"Clasificacion.xlsx",
    index=False
)