# -*- coding: utf-8 -*-
"""Untitled41.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1He4anbzUiWZOB0W9zXkBTut3WUo7PNaF
"""

!python -m spacy download es_core_news_md

import re
import spacy

# Cargar modelo una sola vez
nlp = spacy.load("es_core_news_md")

PALABRAS_INDIGENAS = {
    "ihuatsï", "misitu", "sapichu", "turhípiti", "pireri",
    "kukuta", "uarhi", "uichu", "túkuru", "auani",
    "kani", "jarhámuta", "uátsï", "uátsi",
    "axuni", "kuini", "tzintzun", "kuaraki",
    "kurhikaueri", "kutsi", "kutzi", "koki", "kuanasi",
    "kuiris", "japunda", "japonda", "akuitse"
}

STOPWORDS_EXTRA = {
    "el", "la", "los", "las", "lo", "uno", "este", "ese", "esta", "eso", "él",
    "a", "de", "del", "al", "en", "con", "por", "para", "sin", "sobre", "entre", "hasta",
    "y", "o", "ni", "pero", "porque", "si", "como", "cuando",
    "yo", "tú", "tu", "me", "te", "se", "le", "nos", "mi", "mis", "su", "sus",
    "otros", "que", "qué", "ya", "muy", "más", "tan", "todo", "todos",
    "bien", "así", "donde", "ay", "un", "una", "no", "es", "ir", "ser",
    "lai", "ver", "hay"
}

PALABRAS_CORTE = ["Dura:", "Tema:", "Personajes:"]

RE_AUTOR = re.compile(r'^autor\s*[:\.]?\s*', re.IGNORECASE)
RE_PARENTESIS = re.compile(r'\(.*?\)', re.DOTALL)


def clasificar_cancion(
    texto_raw,
    nombre_cancion="Cancion",
    umbral_estandar=5.0,
    umbral_regional=18.0
):
    """
    Recibe el contenido completo del archivo TXT y el nombre de la canción.
    Regresa:
        ESPAÑOL_ESTANDAR
        ESPAÑOL_REGIONAL
        LENGUA_INDIGENA
    """

    # ---------------------------
    # 1. Eliminar encabezados
    # ---------------------------
    lineas = texto_raw.split("\n")
    idx_inicio = 0

    for i, linea in enumerate(lineas):
        if linea.strip().lower() == nombre_cancion.strip().lower():
            idx_inicio = i + 1
            break

    while idx_inicio < len(lineas) and not lineas[idx_inicio].strip():
        idx_inicio += 1

    if (
        idx_inicio < len(lineas)
        and RE_AUTOR.match(lineas[idx_inicio].strip())
    ):
        idx_inicio += 1

        while idx_inicio < len(lineas) and not lineas[idx_inicio].strip():
            idx_inicio += 1

    texto = "\n".join(lineas[idx_inicio:])

    # ---------------------------
    # 2. Eliminar paréntesis cortos
    # ---------------------------
    def reemplazar(match):
        return match.group(0) if len(match.group(0)) >= 19 else ""

    texto = RE_PARENTESIS.sub(reemplazar, texto)

    # ---------------------------
    # 3. Cortar metadatos finales
    # ---------------------------
    for marca in PALABRAS_CORTE:
        if marca in texto:
            texto = texto.split(marca)[0]

    # ---------------------------
    # 4. Limpieza general
    # ---------------------------
    texto = re.sub(r"\s+", " ", texto.strip())
    texto = texto.replace("|", "").replace("-", "")

    # ---------------------------
    # 5. Clasificación OOV
    # ---------------------------
    doc = nlp(texto.lower())

    n_total = 0
    n_oov = 0
    contiene_indigena = False

    for token in doc:

        if (
            token.is_alpha
            and len(token) > 2
            and not token.is_stop
            and token.lemma_ not in STOPWORDS_EXTRA
            and token.text not in STOPWORDS_EXTRA
        ):

            n_total += 1

            if token.is_oov:
                n_oov += 1

            if (
                token.text in PALABRAS_INDIGENAS
                or token.lemma_ in PALABRAS_INDIGENAS
            ):
                contiene_indigena = True

    pct_oov = 0 if n_total == 0 else (100 * n_oov / n_total)

    if contiene_indigena:
        return "LENGUA_INDIGENA"

    if pct_oov < umbral_estandar:
        return "ESPAÑOL_ESTANDAR"
    elif pct_oov < umbral_regional:
        return "ESPAÑOL_REGIONAL"
    else:
        return "LENGUA_INDIGENA"