version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25"

linters:
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    govet:
      enable:
        - shadow

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - testifylint

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
