-- 008_password_reset_tokens.sql
-- Stores short-lived, single-use tokens used by the password
-- recovery flow. Tokens are stored hashed (bcrypt) so a DB leak
-- does not yield usable reset links. The user-facing plaintext
-- token is generated by the backend on POST /api/auth/forgot,
-- embedded in a URL mailed to the user, and never persisted.
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         INTEGER NOT NULL,
    token_hash      TEXT NOT NULL UNIQUE,
    expires_at      DATETIME NOT NULL,
    used_at         DATETIME,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id
    ON password_reset_tokens(user_id);

-- Outbox for the email_service fallback. When Resend is not
-- configured the backend writes the would-be email here so
-- operators (and the admin audit page) can inspect it in demo.
CREATE TABLE IF NOT EXISTS email_outbox (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    to_addr         TEXT NOT NULL,
    subject         TEXT NOT NULL,
    body_text       TEXT NOT NULL,
    body_html       TEXT,
    kind            TEXT NOT NULL,
    related_user_id INTEGER,
    delivered_at    DATETIME,
    failed_at       DATETIME,
    failure_reason  TEXT,
    sent_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (related_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_email_outbox_kind
    ON email_outbox(kind);
