"""initial schema (no-op when tables already exist)

Revision ID: 96f3e399e38d
Revises:
Create Date: 2026-07-13 20:03:04.084424+00:00

This migration was autogenerated for a fresh DB. In production the
``letras.db`` is seeded by the Go ``cmd/build-db`` CLI in the
``db-init`` Docker sidecar, which creates the legacy columns
(``fonogramas``, ``songs``, ``users``, ``song_stats``). The FastAPI
models declare additional columns (``audit_log``,
``email_outbox``, ``password_reset_tokens``,
``refresh_token_revocations``) and a few extras on the legacy tables
(``autor``, ``compositor``, ``duracion``, ``personajes``,
``temas_raw``, ``editora``, ``last_sign_in_method``,
``last_sign_in_at``).

To avoid re-creating tables that already exist on a Go-seeded DB,
this upgrade is a no-op when any of the legacy tables are present.
The follow-up migration (``f6f8e399e38d``) handles the missing
columns additively.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96f3e399e38d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tables the Go db-init creates (legacy schema). Used to decide whether
# this migration is a no-op.
_LEGACY_TABLES = frozenset({"fonogramas", "songs", "users", "song_stats"})


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    if _LEGACY_TABLES.issubset(existing):
        # Go-seeded DB; the legacy tables exist. The follow-up migration
        # ``f6f8e399e38d`` will add the FastAPI-only columns. This upgrade
        # is a no-op.
        return

    # Fresh DB: create every table from scratch.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_actor_id"), ["actor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_log_occurred_at"), ["occurred_at"], unique=False
        )

    op.create_table(
        "fonogramas",
        sa.Column("clave_fonograma", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("titulo", sa.String(), nullable=False),
        sa.Column("subtitulo", sa.String(), nullable=True),
        sa.Column("interprete_principal", sa.String(), nullable=True),
        sa.Column("interpretes_invitados", sa.String(), nullable=True),
        sa.Column("interprete_participante", sa.String(), nullable=True),
        sa.Column("soporte_fisico", sa.String(), nullable=True),
        sa.Column("editora", sa.String(), nullable=True),
        sa.Column("numero_catalogo", sa.String(), nullable=True),
        sa.Column("ciudad_edicion", sa.String(), nullable=True),
        sa.Column("pais_edicion", sa.String(), nullable=True),
        sa.Column("anio", sa.String(), nullable=True),
        sa.Column("pistas", sa.String(), nullable=True),
        sa.Column("observaciones", sa.String(), nullable=True),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.PrimaryKeyConstraint("clave_fonograma"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.String(),
            nullable=False,
            server_default=sa.text("'viewer'"),
        ),
        sa.Column("last_sign_in_method", sa.String(), nullable=True),
        sa.Column("last_sign_in_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fonograma_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("lyrics", sa.String(), nullable=True),
        sa.Column("clasificacion", sa.String(), nullable=True),
        sa.Column("tema", sa.String(), nullable=True),
        sa.Column("autor", sa.String(), nullable=True),
        sa.Column("compositor", sa.String(), nullable=True),
        sa.Column("duracion", sa.String(), nullable=True),
        sa.Column("personajes", sa.String(), nullable=True),
        sa.Column("temas_raw", sa.String(), nullable=True),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fonograma_id"], ["fonogramas.clave_fonograma"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_songs_fonograma_id"), ["fonograma_id"], unique=False
        )

    op.create_table(
        "song_stats",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("pct_oov", sa.Float(), nullable=False),
        sa.Column("categoria", sa.String(), nullable=False),
        sa.Column("contiene_indigena", sa.Integer(), nullable=False),
        sa.Column("n_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"], ["songs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("song_id"),
    )

    op.create_table(
        "email_outbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("to_addr", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body_text", sa.String(), nullable=False),
        sa.Column("body_html", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("related_user_id", sa.Integer(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.Column(
            "sent_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["related_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_outbox", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_outbox_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_outbox_related_user_id"),
            ["related_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_email_outbox_to_addr"), ["to_addr"], unique=False
        )

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table(
        "password_reset_tokens", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "refresh_token_revocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column(
            "revoked_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    with op.batch_alter_table(
        "refresh_token_revocations", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_refresh_revocations_expires_at", ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_token_revocations_jti"), ["jti"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_token_revocations_user_id"),
            ["user_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = set(inspector.get_table_names())

    # Drop the new tables first; leave the legacy ones in place (the
    # Go db-init will recreate them on next boot).
    for table in (
        "refresh_token_revocations",
        "password_reset_tokens",
        "email_outbox",
        "audit_log",
    ):
        if table in existing:
            op.drop_table(table)
