// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users/{id}/identity": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes the user_identities row(s) for the given user so that\nfuture Google sign-ins with that Google account will not\nmatch this user.",
                "tags": [
                    "admin"
                ],
                "summary": "Unlink a Google identity from a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search songs by title, album, or lyrics with pagination. Honors\nthe shared filter parameters: theme, year_from, year_to,\nclasificacion, album, q.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "songs"
                ],
                "summary": "Search songs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (deprecated alias for q)",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to search in (title, album, lyrics, all)",
                        "name": "field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated theme list; use __none__ for unclassified",
                        "name": "theme",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Inclusive lower bound on year",
                        "name": "year_from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Inclusive upper bound on year",
                        "name": "year_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by clasificacion (ESPAÑOL_ESTANDAR, ESPAÑOL_REGIONAL, LENGUA_INDIGENA)",
                        "name": "clasificacion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact album match",
                        "name": "album",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field (id, clave, title, album, year, filename, clasificacion)",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc, desc)",
                        "name": "order_dir",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/song/{song_id}": {
            "get": {
                "description": "Get detailed information about a song by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "songs"
                ],
                "summary": "Get song detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Song ID",
                        "name": "song_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SongDetail"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Returns aggregate metrics for the dashboard. Honors the\nshared filter query parameters: theme, year_from, year_to,\nclasificacion, album, q.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get database statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated theme list; use __none__ for unclassified",
                        "name": "theme",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Inclusive lower bound on year",
                        "name": "year_from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Inclusive upper bound on year",
                        "name": "year_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated classification list",
                        "name": "clasificacion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact album match",
                        "name": "album",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search across title, lyrics, and album",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.StatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/timeline": {
            "get": {
                "description": "Get songs grouped by year for the timeline view. Honors the\nshared filter parameters: theme, year_from, year_to,\nclasificacion, album, q. Songs without a year (s/d) are\ngrouped under the literal key \"s/d\" in the response; when a\nyear range is supplied, the s/d bucket is omitted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "songs"
                ],
                "summary": "Get songs timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated theme list; use __none__ for unclassified",
                        "name": "theme",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Inclusive lower bound on year",
                        "name": "year_from",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Inclusive upper bound on year",
                        "name": "year_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated classification list",
                        "name": "clasificacion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exact album match",
                        "name": "album",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Free-text search across title, lyrics, and album",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Song"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/word-cloud": {
            "get": {
                "description": "Returns word frequencies from song lyrics excluding stop words",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get word frequency data for word cloud",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.WordCloudResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AlbumCount": {
            "type": "object",
            "properties": {
                "album": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "handlers.StatsResponse": {
            "type": "object",
            "properties": {
                "avg_lyrics_length": {
                    "type": "number"
                },
                "distinct_themes": {
                    "type": "integer"
                },
                "recently_added": {
                    "type": "integer"
                },
                "songs_by_clasificacion": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "songs_by_indigena": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "songs_by_oov_level": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "songs_by_theme": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "songs_by_year": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "songs_with_lyrics": {
                    "type": "integer"
                },
                "songs_without_year": {
                    "type": "integer"
                },
                "top_albums": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.AlbumCount"
                    }
                },
                "total_albums": {
                    "type": "integer"
                },
                "total_songs": {
                    "type": "integer"
                }
            }
        },
        "handlers.WordCloudResponse": {
            "type": "object",
            "properties": {
                "excludedStopWords": {
                    "type": "integer"
                },
                "totalWords": {
                    "type": "integer"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.WordFreq"
                    }
                }
            }
        },
        "handlers.WordFreq": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "models.LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Song": {
            "type": "object",
            "properties": {
                "album": {
                    "description": "All fonograma columns (joined)",
                    "type": "string"
                },
                "ciudad_edicion": {
                    "type": "string"
                },
                "clasificacion": {
                    "type": "string"
                },
                "editora": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "fonograma_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "interprete_participante": {
                    "type": "string"
                },
                "interprete_principal": {
                    "type": "string"
                },
                "interpretes_invitados": {
                    "type": "string"
                },
                "numero_catalogo": {
                    "type": "string"
                },
                "observaciones": {
                    "type": "string"
                },
                "pais_edicion": {
                    "type": "string"
                },
                "pistas": {
                    "type": "string"
                },
                "soporte_fisico": {
                    "type": "string"
                },
                "subtitulo": {
                    "type": "string"
                },
                "tema": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "models.SongDetail": {
            "type": "object",
            "properties": {
                "album": {
                    "description": "All fonograma columns (joined)",
                    "type": "string"
                },
                "ciudad_edicion": {
                    "type": "string"
                },
                "clasificacion": {
                    "type": "string"
                },
                "editora": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "fonograma_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "interprete_participante": {
                    "type": "string"
                },
                "interprete_principal": {
                    "type": "string"
                },
                "interpretes_invitados": {
                    "type": "string"
                },
                "lyrics": {
                    "type": "string"
                },
                "numero_catalogo": {
                    "type": "string"
                },
                "observaciones": {
                    "type": "string"
                },
                "pais_edicion": {
                    "type": "string"
                },
                "pistas": {
                    "type": "string"
                },
                "soporte_fisico": {
                    "type": "string"
                },
                "subtitulo": {
                    "type": "string"
                },
                "tema": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "models.UserInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Cenidim Songs API",
	Description:      "This is a sample server for Cenidim songs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
